<?php

require_once('wiki_keywords.core.inc');

/**
 * Implementation of hook_menu().
 */

function wiki_keywords_menu() {
  $items = array();
 
  $items['admin/config/content/wiki_keywords'] = array(
    'title' => 'Wiki Keywords',//заголовок страницы
    'description' => 'Wiki Keywords settings',
    'page callback' => 'drupal_get_form',//имя функции
    'page arguments' => array('wiki_keywords_admin_settings_form'),
    'access arguments'  =>  array('access wk admin'),
  );
  
  return $items;
}

function wiki_keywords_admin_settings_form($form) {
  //
  $form['media_settings_default'] = array(
	'#type' => 'fieldset',
	'#title' => t('JW Player default settings'),
	'#collapsible' => TRUE,
	'#collapsed' => FALSE,
  );
  
  $form['media_settings_default']['wiki_keywords_jwplayer_path'] = array(
    '#type' => 'textfield',
    '#title' => t('Jw player plugin path'),
    '#maxlength' => 255,
    '#default_value' => variable_get('wiki_keywords_jwplayer_path', 'sites/all/libraries/jw_player'),
    '#description' => t('The location where Jw player plugin is installed. Relative paths are from the Drupal root directory.'),
    '#required' => TRUE,
  );
  
  $form['media_settings_default']['container'] = array(
	'#type' => 'textfield',
	'#title' => t('Container name'),
	'#maxlength' => '25',
	'#default_value' => variable_get('wiki_keywords_jwplayer_container_name', 'media'),
	'#required' => TRUE,
  );
  
  $form['media_settings_default']['jwplayer_width'] = array(
	'#type' => 'textfield',
	'#title' => t('Width'),
	'#maxlength' => '4',
	'#default_value' => variable_get('wiki_keywords_jwplayer_width', 640),
	'#description' => t('The jwplayer width, in pixels.'),
	'#required' => TRUE,
  );
  
  $form['media_settings_default']['jwplayer_height'] = array(
	'#type' => 'textfield',
	'#title' => t('Height'),
	'#maxlength' => '4',
	'#default_value' => variable_get('wiki_keywords_jwplayer_height', 480),
	'#description' => t('The jwplayer height, in pixels.'),
	'#required' => TRUE,
  );
  
  $form['media_settings_default']['playlist_position'] = array(
	'#type' => 'select',
    '#title' => t('Playlist position'),
    '#default_value' => variable_get('wiki_keywords_jwplayer_playlist_position', t('none')),
    '#options' => array(
      'none' => t('none'), 'over' => t('over'), 'top' => t('top'), 'right' => t('right'), 'left' => t('left'), 'bottom' => t('bottom'),
	),
    
  );
  
  
  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
  
  

  return $form;
}

function wiki_keywords_admin_settings_form_validate(&$form, &$form_state) {
  if (!file_exists($form_state['values']['wiki_keywords_jwplayer_path'])) {
    form_set_error('wiki_keywords_jwplayer_path', 'Folder path jw player plugin not exists');
  }
  return FALSE;
}


function wiki_keywords_admin_settings_form_submit(&$form, &$form_state) {
  //dsm($form_state);
 
  // путь к библиотеке jwplayer
  variable_set('wiki_keywords_jwplayer_path', $form_state['values']['wiki_keywords_jwplayer_path']);
  // conteiner name default
  variable_set('wiki_keywords_jwplayer_container_name', $form_state['values']['container']);
  // player width
  variable_set('wiki_keywords_jwplayer_width', $form_state['values']['jwplayer_width']);
  // player height
  variable_set('wiki_keywords_jwplayer_height',  $form_state['values']['jwplayer_height']);
  // playlist position
  variable_set('wiki_keywords_jwplayer_playlist_position', $form_state['values']['playlist_position']);
  
  
  drupal_set_message(t('Your configuration has been saved.'));
}

function wiki_keywords_permission() {
    return array(
        'acess wk admin' => array(
              'title'           => t('Admin WK'),
              'description'     => t('Access Wiki Keywords settings')
            ),
        );
}

 
function main_function() {
  $form = '';
  return $form . 'Привет мир.';
}


/**
 * Implementation of hook_filter_info().
 */
 
function wiki_keywords_filter_info() {
  $filters['wiki_keywords_filter'] = array(
    'title' => t('Wiki Keywords Filter'),
    'description' => t('Генерация контента на основе wk шаблонов'),
    'process callback' => 'wiki_keywords_filter_process',
    'weight' => -10,
  );
  return $filters;
}

/**
 * Implementation of hook_filter_process().
 */
 
function wiki_keywords_filter_process($text, $filter, $format, $langcode, $cache, $cache_id) {
  $wk = new wk($text);
  $text = $wk->replace();
  return $text;
  
}


function wiki_keywords_form_alter(&$form, &$form_state, $form_id) {
 // dsm($form_id);
}


function wiki_keywords_init() {
  drupal_add_js(variable_get('wiki_keywords_jwplayer_path') . '/jwplayer.js');
}
